### ISSUE TITLE
Memory leak on pytorch0.4.0

### ISSUE THREAD

**Issue by marvis** [PureDiors/pytorch_RFCN#7]
When I train RFCN network, the GPU Memory is growing every batch. After some debug, I locate the bug which is from PSRoIPool. 

But I can't find the exact problem as the code seems quite ok. Can you help to find the problem? 

Thanks and Best,

**Comment by zorrocai** [comment]
Yes, I found the same problem. And I thought  the bug lies in PSROIPool, too. But I didn't locate the problem, though I have read the PSROIPool codes.

**Comment by zorrocai** [comment]
@marvis Have you sloved the memory leak problem?

**Comment by door5719** [comment]
@marvis @zorrocai   I want to know how to solve the problem ......thank you
